// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DgbUx9jxPDBl6jkaZIX2VH7uhatZ8xs',
    appId: '1:107981426242:web:661439ad1531ee152927db',
    messagingSenderId: '107981426242',
    projectId: 'mujfiles',
    authDomain: 'mujfiles.firebaseapp.com',
    databaseURL: 'https://mujfiles-default-rtdb.firebaseio.com',
    storageBucket: 'mujfiles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQci2yDki2XVWacehWy6y6HMlum-54S4o',
    appId: '1:107981426242:android:c5fda05da1da46382927db',
    messagingSenderId: '107981426242',
    projectId: 'mujfiles',
    databaseURL: 'https://mujfiles-default-rtdb.firebaseio.com',
    storageBucket: 'mujfiles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxsNtM9Rswll0_Wg7G2zaeIrr7vMBqqo',
    appId: '1:107981426242:ios:a72a3dbab7e277402927db',
    messagingSenderId: '107981426242',
    projectId: 'mujfiles',
    databaseURL: 'https://mujfiles-default-rtdb.firebaseio.com',
    storageBucket: 'mujfiles.appspot.com',
    iosClientId: '107981426242-uq6mqi6vblfdqhfmfmdahc6ihpls6upi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mujFiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxsNtM9Rswll0_Wg7G2zaeIrr7vMBqqo',
    appId: '1:107981426242:ios:a72a3dbab7e277402927db',
    messagingSenderId: '107981426242',
    projectId: 'mujfiles',
    databaseURL: 'https://mujfiles-default-rtdb.firebaseio.com',
    storageBucket: 'mujfiles.appspot.com',
    iosClientId: '107981426242-uq6mqi6vblfdqhfmfmdahc6ihpls6upi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mujFiles',
  );
}
